from .base import *

DEBUG = True
TEMPLATE_DEBUG = DEBUG


# For django-social-auth
TWITTER_CONSUMER_KEY         = 'DEFINE-ME-HERE--DO-NOT-CHECK-IN-PUBLICLY'
TWITTER_CONSUMER_SECRET      = 'DEFINE-ME-HERE--DO-NOT-CHECK-IN-PUBLICLY'
FACEBOOK_APP_ID              = 'DEFINE-ME-HERE--DO-NOT-CHECK-IN-PUBLICLY'
FACEBOOK_API_SECRET          = 'DEFINE-ME-HERE--DO-NOT-CHECK-IN-PUBLICLY'


# For django-debug-toolbar
INSTALLED_APPS += ('debug_toolbar',)
INTERNAL_IPS = ('127.0.0.1', 'YOUR-IP-ADDRESS-HERE')

DEBUG_TOOLBAR_CONFIG = {
    'INTERCEPT_REDIRECTS': False,
}
